# Nous indiquons ici, le liens vers quoi pointe relative_url.
baseurl: /jekyll-starter

# Nous déclarons une nouvelle collection personnalisée.
collections:
  tutoriels:
    output: true

<<<<<<< HEAD
title: Jekyll starter kit ++
=======
>>>>>>> 5fd832117af2158cd446147c4d41198aa2f7901b
