# Nous indiquons ici, le liens vers quoi pointe relative_url.
baseurl: /jekyll-starter

# Nous déclarons une nouvelle collection personnalisée.
collections:
  tutoriels:
<<<<<<< HEAD
    output: true

title: Jekyll starter kit ++
=======
    output: true
>>>>>>> 6f6126c8d02062f210b8fac2ec32da9ff87bf19c
